### ISSUE TITLE
A few errors...

### ISSUE THREAD

**Issue by OzRoyalOG** [DevMiser/DaVinci#13]
So the script recognises the wake word and then listens... When I ask a question I get the following errors...

You have hit your assigned rate limit.
Traceback (most recent call last):
  File "/home/ozroyalog/DaVinci/DaVinci.py", line 306, in <module>
    (res) = ChatGPT(transcript)
  File "/home/ozroyalog/DaVinci/DaVinci.py", line 71, in ChatGPT
    response = openai.ChatCompletion.create(
  File "/home/ozroyalog/.local/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/ozroyalog/.local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/ozroyalog/.local/lib/python3.9/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/ozroyalog/.local/lib/python3.9/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/home/ozroyalog/.local/lib/python3.9/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: Your account is not active, please check your billing details on our website.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ozroyalog/DaVinci/DaVinci.py", line 345, in <module>
    voice("\nYou have hit your assigned rate limit.")
  File "/home/ozroyalog/DaVinci/DaVinci.py", line 100, in voice
    voiceResponse = polly.synthesize_speech(Text=chat, OutputFormat="mp3",
  File "/home/ozroyalog/.local/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ozroyalog/.local/lib/python3.9/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the SynthesizeSpeech operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

All the Access Keys, APi keys etc are correct... Any ideas?

**Comment by OzRoyalOG** [comment]
So as an update on this... I am now getting an initial response from ChatGPT when running the script. But I also get this error too and no sound...

Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ozroyalog/DaVinci/DaVinci.py", line 100, in voice
    voiceResponse = polly.synthesize_speech(Text=chat, OutputFormat="mp3",
  File "/home/ozroyalog/.local/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ozroyalog/.local/lib/python3.9/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the SynthesizeSpeech operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
