### ISSUE TITLE
AttributeError: module 'pygame' has no attribute 'mixer'

### ISSUE THREAD

**Issue by olskar** [DevMiser/DaVinci#27]
Not sure what to make of this? It detects the hotword but then pygame has a problem

`pi@raspberrypi:~ $ python3 DaVinci/DaVinci.py

DaVinci detected

Traceback (most recent call last):
  File "/home/pi/DaVinci/DaVinci.py", line 303, in <module>
    voice(random.choice(prompt))
  File "/home/pi/DaVinci/DaVinci.py", line 121, in voice
    pygame.mixer.init()
AttributeError: module 'pygame' has no attribute 'mixer'
^Z
[4]+  Stopped                 python3 DaVinci/DaVinci.py
`

**Comment by olskar** [comment]
Solved by running python 3.9 for some reason
