### ISSUE TITLE
Connection to Amazon AWS Broken

### ISSUE THREAD

**Issue by mmollet** [DevMiser/DaVinci#31]
Havent changed anything and doublechecked Keys, created new user, updated all plugins with pip, tried really anything to get rid of that. It worked for 4 days without modifying anything.

jarvis detected

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/botocore/httpsession.py", line 451, in send
    conn = manager.connection_from_url(request.url)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 297, in connection_from_url
    u = parse_url(url)
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 394, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 2, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://polly.eu-central-1.amazonaws.com/v1/speech

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/jarvis/DaVinci/DaVinci/DaVinci_Allg.py", line 323, in <module>
    voice(random.choice(prompt))
  File "/home/pi/jarvis/DaVinci/DaVinci/DaVinci_Allg.py", line 114, in voice
    voiceResponse = polly.synthesize_speech(Text=chat, Engine="neural", OutputFormat="mp3",
  File "/home/pi/.local/lib/python3.9/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/botocore/client.py", line 989, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/pi/.local/lib/python3.9/site-packages/botocore/client.py", line 1015, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/pi/.local/lib/python3.9/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/pi/.local/lib/python3.9/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
  File "/home/pi/.local/lib/python3.9/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
  File "/home/pi/.local/lib/python3.9/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/home/pi/.local/lib/python3.9/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "/home/pi/.local/lib/python3.9/site-packages/botocore/retryhandler.py", line 307, in _should_retry
    return self._checker(
  File "/home/pi/.local/lib/python3.9/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/home/pi/.local/lib/python3.9/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/home/pi/.local/lib/python3.9/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/home/pi/.local/lib/python3.9/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/home/pi/.local/lib/python3.9/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/home/pi/.local/lib/python3.9/site-packages/botocore/httpsession.py", line 509, in send
    raise HTTPClientError(error=e)
botocore.exceptions.HTTPClientError: An HTTP Client raised an unhandled exception: Failed to parse: https://polly.eu-central-1.amazonaws.com/v1/speech

**Comment by DevMiser** [comment]
It appears you are not connecting with your regional AWS.  I that problem persists, you may want to use the DaVinciAltVoice.py file I recently added to this repository.  It uses OpenAI’s text-to-speech model instead of Amazon Polly.

**Comment by mmollet** [comment]
thank you very much, i really liked the neural German speaking guy, will try to fix it somehow but iam in Germany and connecting to aws Frankfurt,  so i dont quite understand what is the misstake here though it worked for 4 days without me changing anything. But Thanks for the alternative file it helps checking if anything else is still working !
