### ISSUE TITLE
Failed to initialize pv_recorder

### ISSUE THREAD

**Issue by t0mer** [DevMiser/DaVinci#8]
Hi, 
I am running on Rpi 4 with 4G memory, 128GB sd card, and 64bit os.
The Wakeup word is working, but second after the response, I'm getting the following error:

```Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/opt/webplant/app.py", line 281, in run
    recorder = PvRecorder(device_index=-1, frame_length=1024)
  File "/usr/local/lib/python3.9/dist-packages/pvrecorder/pvrecorder.py", line 81, in __init__
    raise self._PVRECORDER_STATUS_TO_EXCEPTION[status]("Failed to initialize pv_recorder.")
RuntimeError: Failed to initialize pv_recorder.
```

Thanks

**Comment by jimbo0378** [comment]
Did you find a solution? I'm running into the same issue
